### ISSUE TITLE
Error in arithmetic operations for Nodes of depth > 1

### ISSUE THREAD

**Issue by jvadair** [jvadair/pyntree#13]
To replicate:
```python
>>> from pyntree import Node
>>> x = Node()
>>> x.a = {}
>>> x.a.b = 1
>>> x.a.b += 1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jvadair/.local/lib/python3.10/site-packages/pyntree/__init__.py", line 210, in __iadd__
    self.file.data[self.path[0]] += other
TypeError: unsupported operand type(s) for +=: 'dict' and 'int'
>>> 
```
Basically, pyntree needs to get the child Node using all of its path arguments and then modify it.

**Comment by CarterKJ** [comment]
Dear Pyntree Development Team,

I hope this message finds you well. I am writing to address a specific issue that I encountered while using Pyntree, specifically related to arithmetic operations on nodes with a depth greater than one.

During my usage of Pyntree, I observed that when attempting to modify a child Node using its complete path arguments, an error occurs. Allow me to provide you with an example to illustrate the issue:
```python
>>> from pyntree import Node
>>> x = Node()
>>> x.a = {}
>>> x.a.b = 1
>>> x.a.b += 1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python3.10/site-packages/pyntree/__init__.py", line 210, in __iadd__
    self.file.data[self.path[0]] += other
TypeError: unsupported operand type(s) for +=: 'dict' and 'int'
```
As demonstrated above, when attempting to increment the value of the child Node x.a.b by 1, the TypeError is raised. The error message indicates that the operand types for += are unsupported: 'dict' and 'int'.

Upon further analysis, it appears that the issue stems from Pyntree's method of retrieving and modifying the child Node. It seems that Pyntree fails to correctly identify the child Node using its complete path arguments, leading to the aforementioned error.

To address this issue, I suggest implementing a fix that ensures Pyntree retrieves the correct child Node using all of its path arguments and subsequently allows for the modification to take place without encountering the error.

I appreciate your attention to this matter and your ongoing efforts in maintaining and improving Pyntree. Please let me know if you require any additional information or if I can assist you further in any way.

Thank you for your time and support.

**Comment by jvadair** [comment]
@CarterKJ https://github.com/jvadair/pyntree/issues/13#issuecomment-1559743891
Did you really just ask ChatGPT to rewrite my issue as a formal letter
